# Generated by Django 5.0.7 on 2024-07-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='lent_to',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
